/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDystopiaFactory,
  IDystopiaFactoryInterface,
} from "../../interfaces/IDystopiaFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token1",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "stable",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "address",
        name: "pair",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "allPairsLength",
        type: "uint256",
      },
    ],
    name: "PairCreated",
    type: "event",
  },
] as const;

export class IDystopiaFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IDystopiaFactoryInterface {
    return new utils.Interface(_abi) as IDystopiaFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDystopiaFactory {
    return new Contract(address, _abi, signerOrProvider) as IDystopiaFactory;
  }
}
