/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFirebirdFactory,
  IFirebirdFactoryInterface,
} from "../../interfaces/IFirebirdFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token1",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "pair",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "tokenWeight0",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "swapFee",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "allPairsLength",
        type: "uint256",
      },
    ],
    name: "PairCreated",
    type: "event",
  },
] as const;

export class IFirebirdFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IFirebirdFactoryInterface {
    return new utils.Interface(_abi) as IFirebirdFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFirebirdFactory {
    return new Contract(address, _abi, signerOrProvider) as IFirebirdFactory;
  }
}
