/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDystopiaFactory__factory } from "./IDystopiaFactory__factory";
export { IFirebirdFactory__factory } from "./IFirebirdFactory__factory";
