/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDystopiaFactory } from "./IDystopiaFactory";
export type { IFirebirdFactory } from "./IFirebirdFactory";
